int vendasExiste();
void adicionarVendas();
void listarVendas();
void listarVendasCliente();
void listarVendasPacote();
void removerVendas();
void removerVendasCliente();
void removerVendasPacote();
void menuVendas();
